#!/usr/bin/env python3
"""
wisdom-card-scaffold.py — I-NEW-28
==================================
SAKM v2 Wisdom Card Auto-Scaffold (K.21)
Owner: KM #51 + Senior Content #27
Promoted: 29 Apr 2026 (K.21 ARAI)

Purpose
-------
Reduce manual format work for Senior Content #27 during Phase 2
(target ≥500 Tier-1 Wisdom Cards). Generates compliant skeleton from
a few CLI args; Senior Content #27 fills in the wisdom prose only.

Schema enforced from K.21 charter.

Outputs
-------
  sakm/wisdom-cards/{category}/WC-{category}-{YYYYMMDD}-{seq}.md

Usage
-----
  python3 scripts/wisdom-card-scaffold.py \\
      --category strategy \\
      --title "Founder turnaround thesis 2026" \\
      --source-uri "file:///{driveId}/{itemId}" \\
      --source-path "/Shared Documents/New Business/Able AI/.../strategy.html" \\
      --source-modified 2026-04-21 \\
      --sensitivity INTERNAL \\
      --target-agents "5,13,25,65" \\
      --synthesizer "#25" \\
      --out-root sakm/wisdom-cards/

Run with --list-categories to see all 12 canonical categories.
"""
from __future__ import annotations

import argparse
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from textwrap import dedent

CATEGORIES = [
    "strategy", "finance", "sales", "marketing", "product",
    "tech", "legal", "hr", "client_records", "operations",
    "founder_story", "historical_decisions",
]
SENSITIVITY = ["PUBLIC", "INTERNAL", "CONFIDENTIAL", "SECRET"]
SLUG_RE = re.compile(r"[^a-z0-9]+")


def slugify(s: str, max_len: int = 40) -> str:
    s = SLUG_RE.sub("-", s.lower()).strip("-")
    return s[:max_len]


def next_seq(out_dir: Path, prefix: str) -> int:
    if not out_dir.exists():
        return 1
    existing = list(out_dir.glob(f"{prefix}-*.md"))
    nums = []
    for p in existing:
        try:
            nums.append(int(p.stem.rsplit("-", 1)[-1]))
        except ValueError:
            continue
    return (max(nums) + 1) if nums else 1


def render_card(args: argparse.Namespace, card_id: str) -> str:
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    targets = ", ".join(f"#{a.strip().lstrip('#')}" for a in args.target_agents.split(",") if a.strip())
    return dedent(f"""\
        ---
        id: {card_id}
        title: {args.title}
        category: {args.category}
        context: TODO_FILL_1_2_SENTENCES
        key_numbers: []
        lessons_learned: []
        target_agents: [{targets}]
        sensitivity_tag: {args.sensitivity}
        source_uri: {args.source_uri}
        source_path: {args.source_path}
        source_last_modified: {args.source_modified}
        synthesizer: {args.synthesizer}
        qa_layer1: TODO_AGENT_ID
        review_layer2: TODO_CWO_OR_65CDA
        created: {today}
        status: DRAFT
        ---

        # {args.title}

        ## Context
        TODO — 1–2 sentences anchoring the wisdom in business context.

        ## Key Numbers
        - TODO

        ## Lessons Learned
        - TODO

        ## Application — Target Agents
        {targets} — TODO note how each agent should apply this wisdom.

        ## Source
        - File: `{args.source_path}`
        - URI: `{args.source_uri}`
        - Last modified: {args.source_modified}

        ## Review Trail (auto-filled later)
        - Synthesizer: {args.synthesizer}
        - QA Layer-1: TODO (Op 11)
        - Review Layer-2: TODO (Op 12 · CWO or #65 CDA)

        ---
        *Generated by wisdom-card-scaffold.py · I-NEW-28 · {today}*
    """)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--list-categories", action="store_true")
    ap.add_argument("--category", choices=CATEGORIES)
    ap.add_argument("--title")
    ap.add_argument("--source-uri")
    ap.add_argument("--source-path")
    ap.add_argument("--source-modified", help="YYYY-MM-DD")
    ap.add_argument("--sensitivity", choices=SENSITIVITY, default="INTERNAL")
    ap.add_argument("--target-agents", help="Comma-separated agent IDs e.g. 5,13,25,65")
    ap.add_argument("--synthesizer", help="Agent ID e.g. #25")
    ap.add_argument("--out-root", type=Path, default=Path("sakm/wisdom-cards"))
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    if args.list_categories:
        print("\n".join(CATEGORIES))
        return 0

    required = ["category", "title", "source_uri", "source_path", "source_modified", "target_agents", "synthesizer"]
    missing = [r for r in required if getattr(args, r) in (None, "")]
    if missing:
        ap.error(f"missing required args: {', '.join(missing)}")

    out_dir = args.out_root / args.category
    today_compact = datetime.now(timezone.utc).strftime("%Y%m%d")
    prefix = f"WC-{args.category}-{today_compact}"
    seq = next_seq(out_dir, prefix)
    card_id = f"{prefix}-{seq:03d}"
    card_slug = slugify(args.title)
    out_path = out_dir / f"{card_id}-{card_slug}.md"

    body = render_card(args, card_id)

    if args.dry_run:
        print(body)
        print(f"\n# would write: {out_path}", file=sys.stderr)
        return 0

    out_dir.mkdir(parents=True, exist_ok=True)
    if out_path.exists():
        print(f"[err] refuse to overwrite: {out_path}", file=sys.stderr)
        return 2
    out_path.write_text(body, encoding="utf-8")
    print(f"created {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
